import type { Metadata } from "next";
import { Inter } from "next/font/google";
/* import "./globals.css"; */
import { Providers } from "../provider/ThemeProvider";
import Header from "@/components/header/Header";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../assets/scss/style.scss";
import Footer from "@/components/footer/Footer";
import { memo } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html >
  );
}
